name: End-to-end tests
on: [push] #Será disparado sempre que houver um 'push'
jobs: 
  cypress-run:
    runs-on: ubuntu-20.04 #A imagem onde os testes serão rodados
    steps:                #Passos que serão rodados
      - name: Checkout    #P/ o github baixar o código do projeto no workspace do github actions
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Cypress run #P/ o github rodar o código do projeto uaando a imagem cypress-io/github-action@v2
        uses: cypress-io/github-action@v3